CREATE TABLE products (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(500) NOT NULL,
    name_ar VARCHAR(500) NOT NULL,
    slug VARCHAR(500) NOT NULL UNIQUE,
    description TEXT,
    description_ar TEXT,
    price DECIMAL(10,2) NOT NULL,
    category_id UUID NOT NULL,
    brand VARCHAR(255),
    images JSONB DEFAULT '[]',
    rating DECIMAL(3,2) DEFAULT 0,
    review_count INTEGER DEFAULT 0,
    prescription_required BOOLEAN DEFAULT false,
    stock_quantity INTEGER DEFAULT 0,
    formulation VARCHAR(255),
    composition TEXT,
    indications TEXT,
    contraindications TEXT,
    usage_instructions TEXT,
    safety_notes TEXT,
    sku VARCHAR(100) UNIQUE,
    is_featured BOOLEAN DEFAULT false,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);